version: '3.8'

services:
  fastapi:
    image: image
    container_name: image-service
    command: uvicorn service:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - /opt/novavision/image:/opt/project
    ports:
      - 8000:8000
